name: Validate workflow
'on':
  pull_request:
    branches:
      - main
jobs:
  validate:
    name: Validate workflow is in sync with code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Setup Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Generate pipelines
        run: npm run compile:pipeline
      - name: Validate pipelines
        run: test -z "$(git status --porcelain)"
